NGT/Models/Entities/Ocorrencia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NGT.Models.Entities
{
    public class Ocorrencia
    {
        public int Id { get; set; }
        [MaxLength(250)]
        public string Obs { get; set; }
        public string InfoAtualizacao { get; set; }
        //public string Imagem { get; set; }
        public DateTime DataCriacao { get; set; }
        public DateTime? DataAtualizacao { get; set; }
        public string NumTicket { get; set; }
        public string FotoOcorrencia { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public int BlocoId { get; set; }
        [Required]
        public int LocalId { get; set; }
        [Required]
        public int CategoriaId { get; set; }
        [Required]
        public int ItemId { get; set; }
        [Required]
        public int MotivoId { get; set; }
        [Required]
        public int StatusTicketId { get; set; }
        
        public Ocorrencia()
        {
            DataCriacao = DateTime.Now;
        }


        public virtual Bloco Bloco { get; set; }
        public virtual Local Local { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Item Item { get; set; }
        public virtual Motivo Motivo { get; set; }
        public virtual StatusTicket StatusTicket { get; set; }

    }
}

NGT/Areas/Admin/Controllers/OcorrenciaController.cs
using NGT.Application;
using NGT.Data;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NGT.Models.Entities;
using System.Net.Sockets;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;

namespace NGT.Areas.Admin.Controllers
{
    public class OcorrenciaController : AdminController
    {
        private NgtContexto db = new NgtContexto();
        // GET: Admin/Ocorrencia
        public ActionResult Index()
        {
            ViewBag.Ocorrencias = db.Ocorrencias.Include(x => x.Bloco).Include(x => x.Categoria).Include(x => x.Item).Include(x => x.Local).Include(x => x.Motivo).Include(x => x.StatusTicket).ToList();

            //ViewBag.StatusTicketsId = db.StatusTickets.ToList();

            ViewBag.Pendente = db.Ocorrencias.Include(x => x.StatusTicket).Where(x => x.StatusTicket.Nome == "Pendente").Count();
            ViewBag.Andamento = db.Ocorrencias.Include(x => x.StatusTicket).Where(x => x.StatusTicket.Nome == "Em Andamento").Count();
            ViewBag.Concluido = db.Ocorrencias.Include(x => x.StatusTicket).Where(x => x.StatusTicket.Nome == "Concluído").Count();
            ViewBag.Cancelado = db.Ocorrencias.Include(x => x.StatusTicket).Where(x => x.StatusTicket.Nome == "Cancelado").Count();

            return View("Ocorrencia");
        }

        public ActionResult Criar()
        {
            ViewBag.BlocoId = new SelectList(db.Blocos.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            ViewBag.CategoriaId = new SelectList(db.Categorias.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            ViewBag.MotivoId = new SelectList(db.Motivos.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            return View("NovaOcorrencia");
        }

        [HttpPost, ValidateAntiForgeryToken]
        [Obsolete]
        public ActionResult Criar(Ocorrencia Oco, HttpPostedFileBase FotoOcorrencia)
        {
            if (ModelState.IsValid)
            {
                string valor = "";
                var email = db.Usuarios.Find(Convert.ToInt32(User.Identity.Name.Split('|')[0]));
                var nomeBloco = db.Blocos.Where(x => x.Id == Oco.BlocoId).FirstOrDefault().Nome;
                var letraBloco = nomeBloco.Substring(nomeBloco.Length - 1, 1);
                var idoco = 0;
                if (db.Ocorrencias.FirstOrDefault() != null)
                {
                    idoco = db.Ocorrencias.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                    idoco++;
                }

                var ticket = letraBloco + idoco + DateTime.Now.Day + DateTime.Now.Second;

                Ocorrencia ocorrencia = new Ocorrencia
                {
                    Obs = Oco.Obs,
                    NumTicket = ticket,
                    FotoOcorrencia = Oco.FotoOcorrencia,
                    BlocoId = Oco.BlocoId,
                    LocalId = Oco.LocalId,
                    CategoriaId = Oco.CategoriaId,
                    ItemId = Oco.ItemId,
                    MotivoId = Oco.MotivoId,
                    Email = email.Email,
                    StatusTicketId = db.StatusTickets.Where(x => x.Nome == "Pendente").FirstOrDefault().Id
                };

                db.Ocorrencias.Add(ocorrencia);
                db.SaveChanges();

                if (FotoOcorrencia != null)
                {
                    Funcoes.CriarDiretorio(ocorrencia.NumTicket);
                    string nomearq = "FotoOcorrencia" + ocorrencia.NumTicket + ".png";
                    valor = Funcoes.UploadArquivo(FotoOcorrencia, nomearq, ocorrencia.NumTicket);
                    if (valor == "sucesso")
                    {
                        ocorrencia.FotoOcorrencia = "\\Areas\\Admin\\Content\\Images\\" + ocorrencia.NumTicket + "\\" + nomearq;
                        db.Entry(ocorrencia).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["MSG"] = "success|Seu chamado foi registrado com sucesso!|" + ticket;
                        return RedirectToAction("Index", "Ocorrencia");
                    }
                }

                TempData["MSG"] = "success|Seu chamado foi registrado com sucesso!|" + ticket;
                return RedirectToAction("Index", "Ocorrencia");
            }
            TempData["MSG"] = "warning|Preencha todos os campos|x";
            return RedirectToAction("Index", "Ocorrencia");
        }

        [HttpPost]
        public ActionResult CarregaLocal(int blocoId)
        {
            var locais = (from l in db.Locais.Include(x => x.Bloco).Include(x => x.Status)
                          where l.Bloco.Id == blocoId && l.Status.Nome == "Ativado"
                          select new
                          {
                              id = l.Id,
                              nome = l.Nome
                          }).ToArray();
            return Json(locais);
        }
        [HttpPost]
        public ActionResult CarregaItem(int localId, int categId)
        {
            var itens = (from i in db.ItemDescs.Include(x => x.Item).Include(x => x.Local).Include(x => x.Categoria).Include(x => x.Status)
                         where i.Local.Id == localId && i.CategoriaId == categId && i.Status.Nome == "Ativado"
                         select new
                         {
                             id = i.Item.Id,
                             nome = i.Item.Nome,
                         }).Distinct().ToArray();
            return Json(itens);
            //ViewBag.ItemId = new SelectList(db.ItemDescs.Include(x => x.Item).Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Item.Nome");
        }

        public ActionResult TrocarStatus(string id)
        {
            Ocorrencia oco = db.Ocorrencias.Find(Convert.ToInt32(id));
            if (oco != null)
            {
                ViewBag.ocorencia = oco;
                ViewBag.StatusTicketId = new SelectList(db.StatusTickets.OrderByDescending(s => s.Id), "Id", "Nome", oco.StatusTicketId);

            }
            return View("EditaOcorrencia");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult TrocarStatus(int Id, int StatusTicketId, string InfoAtualizacao)
        {
            try
            {
                Ocorrencia oco = db.Ocorrencias.Find(Convert.ToInt32(Id));
                if (oco != null)
                {
                    if (oco.StatusTicketId != StatusTicketId || InfoAtualizacao != "")
                    {
                        oco.StatusTicketId = StatusTicketId;
                        oco.DataAtualizacao = DateTime.Now;
                        if (InfoAtualizacao != "")
                        {
                            if (oco.InfoAtualizacao != null)
                            {
                                oco.InfoAtualizacao = "● " + InfoAtualizacao + " - Data: " + oco.DataAtualizacao + " | " + oco.InfoAtualizacao;
                            } else
                            {
                                oco.InfoAtualizacao = "● " + InfoAtualizacao + " - Data: " + oco.DataAtualizacao;
                            }
                            
                        }
                        db.Entry(oco).State = EntityState.Modified;
                        db.SaveChanges();

                        TempData["MSG"] = "success|Status alterado com sucesso!|x";
                        if (oco.Email != null)
                        {
                            string msg = "<h3>Sistema NewGen Tech</h3>";
                            msg += "<p>Seu chamado " + oco.NumTicket + " teve uma atualização. </p>";
                            if (InfoAtualizacao != "")
                            {
                                msg += "<p>Comentário adicionado: " + oco.InfoAtualizacao + "</p>";
                            }
                                msg += "<p>Status Atualizado: " + oco.StatusTicket.Nome + "</p>";
                            msg +="<p>Para consultar o seu chamado, utilize o código abaixo no campo de consulta do site:</p><p> Chamado registrado - " + oco.NumTicket + " </p>";
                            Funcoes.EnviarEmail(oco.Email, "Alteração no seu chamado!", msg);
                        }
                        return Index();
                    }
                    else
                    {
                        TempData["MSG"] = "info|Nenhuma alteração de status foi realizada!|x";
                        return Index();
                    }

                }
                TempData["MSG"] = "warning|Preencha todos os campos!|x";
                return Index();
            }
            catch (Exception)
            {
                @TempData["MSG"] = "error|Não foi possível alterar o status. Tente novammente!|x";
                return Index();
            }
        }

    }
}

NGT/Controllers/OcorrenciasController.cs
using NGT.Data;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NGT.Models.Entities;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Web.UI.HtmlControls;
using System.Text;
using System.Security.Cryptography;

namespace NGT.Controllers
{
    
    public class OcorrenciasController : Controller
    {
        private NgtContexto db = new NgtContexto();

        public ActionResult Criar()
        {
            ViewBag.BlocoId = new SelectList(db.Blocos.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            ViewBag.CategoriaId = new SelectList(db.Categorias.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            ViewBag.MotivoId = new SelectList(db.Motivos.Include(x => x.Status).Where(x => x.Status.Nome == "Ativado"), "Id", "Nome");
            return View("NovaOcorrencia");
        }

        [HttpPost, ValidateAntiForgeryToken]
        [Obsolete]
        public ActionResult Criar(Ocorrencia Oco, HttpPostedFileBase FotoOcorrencia)
        {
            if (ModelState.IsValid)
            {
                string valor = "";
                var nomeBloco = db.Blocos.Where(x => x.Id == Oco.BlocoId).FirstOrDefault().Nome;
                var letraBloco = nomeBloco.Substring(nomeBloco.Length - 1, 1);
                var idoco = 0;
                if (db.Ocorrencias.FirstOrDefault() != null)
                {
                    idoco = db.Ocorrencias.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                    idoco++;
                }

                var ticket = letraBloco + idoco + DateTime.Now.Day + DateTime.Now.Second;

                Ocorrencia ocorrencia = new Ocorrencia();
                ocorrencia.Obs = Oco.Obs;
                ocorrencia.NumTicket = ticket;
                ocorrencia.FotoOcorrencia = "\\Areas\\Admin\\Content\\Images\\imgNoFound.png";
                ocorrencia.Email = Oco.Email;
                ocorrencia.BlocoId = Oco.BlocoId;
                ocorrencia.LocalId = Oco.LocalId;
                ocorrencia.CategoriaId = Oco.CategoriaId;
                ocorrencia.ItemId = Oco.ItemId;
                ocorrencia.MotivoId = Oco.MotivoId;
                ocorrencia.StatusTicketId = db.StatusTickets.Where(x => x.Nome == "Pendente").FirstOrDefault().Id;

                db.Ocorrencias.Add(ocorrencia);
                db.SaveChanges();

                if (FotoOcorrencia != null)
                {
                    //Funcoes.CriarDiretorio(ocorrencia.NumTicket);
                    string nomearq = "FotoOcorrencia" + ocorrencia.NumTicket + ".png";
                    valor = Funcoes.UploadArquivo(FotoOcorrencia, nomearq, ocorrencia.NumTicket);
                    if (valor == "sucesso")
                    {
                        ocorrencia.FotoOcorrencia = "\\Areas\\Admin\\Content\\Images\\" + ocorrencia.NumTicket + "\\" + nomearq;
                        db.Entry(ocorrencia).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["MSG"] = "success|Seu chamado foi registrado com sucesso!|" + ticket;
                        return RedirectToAction("Index", "Home");
                    }
                }

                TempData["MSG"] = "success|Seu chamado foi registrado com sucesso!|" + ticket;
                if (Oco.Email != null)
                {
                    string msg = "<h3>Sistema NewGen Tech</h3>";
                    msg += "<p>Seu chamado foi registrado com sucesso! Para consultar o seu chamado, utilize o código abaixo no campo de consulta do site:</p><p> Chamado registrado - " + ticket + " </p>";
                    Funcoes.EnviarEmail(Oco.Email, "Registro de Chamado no sistema da Fatec", msg);
                }

                return RedirectToAction("Index", "Home");
            }
            TempData["MSG"] = "warning|Preencha todos os campos|x";
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public ActionResult CarregaLocal(int blocoId)
        {
            var locais = (from l in db.Locais.Include(x => x.Bloco).Include(x => x.Status)
                          where l.Bloco.Id == blocoId && l.Status.Nome == "Ativado"
                          select new
                          {
                              id = l.Id,
                              nome = l.Nome
                          }).ToArray();
            return Json(locais);
        }

        [HttpPost]
        public ActionResult CarregaItem(int localId, int categId)
        {

            var itens = (from i in db.ItemDescs.Include(x => x.Item).Include(x => x.Local).Include(x => x.Categoria).Include(x => x.Status)
                         where i.Local.Id == localId && i.CategoriaId == categId && i.Status.Nome == "Ativado"
                         select new
                         {
                             id = i.Item.Id,
                             nome = i.Item.Nome,
                         }).Distinct().ToArray();
            return Json(itens);
        }

        [HttpGet]
        public ActionResult ConsultaChamado(string termo)
        {
            if (termo == null)
            {
                return View("ConsultaChamado");
            } 
            else
            {
                var encontrado = db.Ocorrencias.Where(x => x.NumTicket == termo).ToList().FirstOrDefault();
                //TempData["LP"] = "x";
                return PartialView("_CarregaChamado", encontrado);
            }

        }


        //Rotas de Carregamento Mobile
        
        [HttpPost]
        public ActionResult BlocoMob()
        {
            //ViewBag.Ocorrencias = db.Ocorrencias.Include(x => x.Bloco).Include(x => x.Categoria).Include(x => x.Item).Include(x => x.Local).Include(x => x.Motivo).Include(x => x.StatusTicket).ToList();
            //var bloco = new SelectList(db.Blocos.Include(x => x.Status)).ToList(); 
            var blocos = (from b in db.Blocos.Include(x => x.Status)
                          where b.Status.Nome == "Ativado"
                          select new
                          {
                              id = b.Id,
                              nome = b.Nome
                          }).ToList();
            return Json(blocos, JsonRequestBehavior.AllowGet);
        }

    }
}

NGT/Views/Ocorrencias/ConsultaChamado.cshtml
@model NGT.Models.Entities.Ocorrencia

@{
    Layout = null;
}

<div class="modal-dialog modal-lg modal-dialog-centered min-vh-100" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title txtBlack" id="ConsultaC">Busca de Chamados</h5>
            <button class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="overflow-hidden">

            <section class="pl-3 pr-3 pt-3 mb-3">
                <div class="row">

                    <div class="col-sm-12">

                        <form method="get" class="d-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control" type="text" id="termo" name="termo" placeholder="Consultar status de chamados">
                                <div class="input-group-append">
                                    <button class="btn input-group-text" id="busca" type="button">
                                        <i class="fas fa-search fa-fw"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>

                    @*<div class="col-sm-6">
                            @if (@TempData["LP"] != null)
                            {
                                <a class="btn btn-default btn-sm float-lg-left float-md-left float-sm-left float-left mr-3" id="novaCateg">
                                    Limpar
                                </a>
                        </div>*@
                </div>


            </section>
            <div id="result" class="txtBlack d-flex justify-content-center ml-3 mr-3"></div>
        </div>
    </div>
</div>


@section ScriptPage{

}

<script>
        $(function () {
            $('#busca').click(function () {
                $('#result').html('<div class="d-flex justify-content-center"><div class="c-loader m-4"></div></div>');

                setTimeout(function () {
                    var termo = $('#termo').val();
                    $.get('@Url.Action("ConsultaChamado","Ocorrencias")', { termo: termo }, function (resultado) {
                        $('#result').removeClass("d-flex justify-content-center");
                        $('#result').html(resultado);
                    });
                }, 1500);


            });
        });

</script>
<script>
    $(".close").click(function () {
        $('#result').html("");
        @*window.location.replace("@Url.RouteUrl("Home.Index")");*@

    });
</script>

NGT/Views/Ocorrencias/NovaOcorrencia.cshtml
@model NGT.Models.Entities.Ocorrencia
@{
    Layout = null;
}

<div class="modal-dialog modal-dialog-centered" role="document" id="novaOco">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title txtBlack" id="NovaOcorrencia">Cadastro de chamados</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="overflow-hidden">
            @using (Html.BeginForm("Criar", "Ocorrencias", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">

                <div class="col-12" id="chamadoBloco1">

                    <div class="form-group">
                        @Html.LabelFor(model => model.BlocoId, "Bloco: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            @Html.DropDownList("BlocoId", null, "Selecione o bloco", htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                        </div>
                    </div>

                    <div class="form-group d-none" id="divLocais">
                        @Html.LabelFor(model => model.LocalId, "Local: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            @Html.DropDownList("LocalId", Enumerable.Empty<SelectListItem>(), htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                        </div>
                    </div>

                    <div class="form-group d-none" id="divCategs">
                        @Html.LabelFor(model => model.CategoriaId, "Categoria: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12  pl-3 pr-3">
                            @Html.DropDownList("CategoriaId", null, "Selecione a Categoria", htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                        </div>
                    </div>

                </div>
                <div class="col-lg-6 col-12">

                    <div class="form-group d-none" id="divItens">
                        @Html.LabelFor(model => model.ItemId, "Item: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            @Html.DropDownList("ItemId", Enumerable.Empty<SelectListItem>(), htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                        </div>
                    </div>

                    <div class="form-group d-none" id="divMotivos">
                        @Html.LabelFor(model => model.MotivoId, "Motivo: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            @Html.DropDownList("MotivoId", null, "Selecione o Motivo", htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                        </div>
                    </div>

                    <div class="form-group d-none" id="divImg">
                        @Html.LabelFor(model => model.FotoOcorrencia, "Deseja carregar uma imagem da ocorrência? ", htmlAttributes: new { @class = "control-label  pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            <div class="input-group">
                                <input type="file" class="form-control-file txtBlack" name="FotoOcorrencia">
                            </div>
                        </div>
                    </div>

                </div>
            </div>
                    <div class="form-group d-none" id="divObs">
                        @Html.LabelFor(model => model.Obs, "Observações: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                        <div class="col-md-12 pl-3 pr-3">
                            @Html.TextAreaFor(model => model.Obs, new { @class = "form-control col-11 col-md-12", rows = "5" })
                        </div>
                    </div>
                    <div class="d-none" id="divSubmit">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, "Deseja receber atualizações de status por email? ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                            <div class="col-md-12 pl-3 pr-3">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control col-11 col-md-12", @placeholder = "E-mail..." } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger text-sm" })
                            </div>
                        </div>

                        <div class="modal-footer justify-content-end col-11 col-md-12">
                            <button type="submit" class="btn btn-default ">Gravar</button>
                        </div>
                    </div>
            }
        </div>
    </div>
</div>

@section ScriptPage{

}
<script>
    $(document).ready(function () {
        $('#BlocoId').change(function () {
            $.ajax({
                url: 'ocorrencias/carregaLocal',
                type: 'POST',
                data: { blocoId: $(this).val() },
                datatype: 'json',
                success: function (data) {
                    var options = '';
                    options += '<option value>Selecione o Local</option>';
                    $.each(data, function () {
                        options += '<option value="' + this.id + '">' + this.nome + '</option>';
                    });
                    $('#LocalId').html(options);
                    $('#divLocais').removeClass('d-none');
                    $('#divCategs').removeClass('d-none');
                },
            });
        });
    });

    $(document).ready(function () {

        $('#CategoriaId').change(function () {
            if ($('#CategoriaId').val() || $('#LocalId').val() !== "") {
                $.ajax({
                    url: 'ocorrencias/carregaitem',
                    type: 'POST',
                    data: {
                        localId: $('#LocalId').val(),
                        categId: $('#CategoriaId').val()
                    },
                    datatype: 'json',
                    success: function (data) {
                        var options = '';
                        options += '<option>Selecione o Item</option>';
                        $.each(data, function () {
                            options += '<option value="' + this.id + '">' + this.nome + '</option>';
                        });
                        $('#ItemId').html(options);
                        $('#chamadoBloco1').addClass("col-lg-6");
                        $('#novaOco').addClass("modal-xl");
                        $('#divItens').removeClass('d-none');
                        $('#divMotivos').removeClass('d-none');
                        $('#divImg').removeClass('d-none');
                        $('#divObs').removeClass('d-none');
                    }
                });
            }
        });

        $('#LocalId').change(function () {
            if ($('#CategoriaId').val() || $('#LocalId').val() !== "") {
                $.ajax({
                    url: 'ocorrencias/carregaitem',
                    type: 'POST',
                    data: {
                        localId: $('#LocalId').val(),
                        categId: $('#CategoriaId').val()
                    },
                    datatype: 'json',
                    success: function (data) {
                        var options = '';
                        options += '<option>Selecione o Item</option>';
                        $.each(data, function () {
                            options += '<option value="' + this.id + '">' + this.nome + '</option>';
                        });
                        $('#ItemId').html(options);
                        $('#divItens').removeClass('d-none');
                        $('#divMotivos').removeClass('d-none');
                        $('#divObs').removeClass('d-none');
                    }
                });
            }
        });

    });

    $(document).ready(function () {
        $('#MotivoId').change(function () {
            $('#divSubmit').removeClass('d-none');
        });
    });
</script>