NGT/Models/Entities/ManutencaoTipo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NGT.Models.Entities
{
    public class ManutencaoTipo
    {
        public int Id { get; set; }
        [Required, MaxLength(100), Index(IsUnique = true)]
        public string Nome { get; set; }
        [Required]
        public int StatusId { get; set; }


        public virtual Status Status { get; set; }

        public virtual ICollection<OrdServico> OrdServico { get; set; }


    }
}

NGT/Areas/Admin/Controllers/ManutencaoTipoController.cs
using NGT.Application;
using NGT.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using NGT.Models.Entities;

namespace NGT.Areas.Admin.Controllers
{
    public class ManutencaoTipoController : AdminController
    {
        private NgtContexto db = new NgtContexto();
        // GET: Admin/ManutencaoTipo
        public ActionResult Listar()
        {
            ViewBag.tipos = db.ManutencaoTipo.ToList().OrderBy(l => l.Nome).OrderByDescending(b => b.StatusId);
            ViewBag.os = db.OrdServicos.Include(x => x.ManutencaoTipo).ToList();
            return View("ListaManutTipos");
        }

        public ActionResult ListarFiltrado(string termo)
        {
            if (string.IsNullOrEmpty(termo))
            {
                @TempData["MSG"] = "warning|Nenhuma busca realizada. Preencha o campo de busca corretamente!|x";
                return Listar();
            }
            ViewBag.tipos = db.ManutencaoTipo.Where(u => u.Nome.ToUpper().Contains(termo.ToUpper())).ToList().OrderBy(u => u.Nome);
            ViewBag.os = db.OrdServicos.Include(x => x.ManutencaoTipo).ToList();
            @TempData["LP"] = "x";
            return View("ListaManutTipos");
        }
        public ActionResult Novo()
        {
            return View("NovoManutTipos");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Novo(ManutencaoTipo tipo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManutencaoTipo manut = new ManutencaoTipo
                    {
                        Nome = tipo.Nome,
                        StatusId = db.Status.Where(x => x.Nome == "Desativado").FirstOrDefault().Id
                    };

                    db.ManutencaoTipo.Add(manut);
                    db.SaveChanges();
                    TempData["MSG"] = "success|Novo tipo registrado com sucesso!|x";
                    return Listar();
                }
                TempData["MSG"] = "error|Preencha todos os campos|x";
                return Listar();
            }
            catch (Exception)
            {
                @TempData["MSG"] = "error|Impossível registrar dois tipos com o mesmo nome!|x";
                return Listar();
            }

        }

        public ActionResult EditaTipos(string id)
        {
            ManutencaoTipo tp = db.ManutencaoTipo.Find(Convert.ToInt32(id));
            if (tp != null)
            {
                ViewBag.tipos = tp;
                ViewBag.StatusId = new SelectList(db.Status.OrderByDescending(s => s.Id), "Id", "Nome", tp.StatusId);

            }
            return View("EditaManutTipos");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditaTipos(ManutencaoTipo tipo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManutencaoTipo tp = db.ManutencaoTipo.Find(tipo.Id);

                    tp.Nome = tipo.Nome;
                    tp.StatusId = tipo.StatusId;

                    db.Entry(tp).State = EntityState.Modified;
                    db.SaveChanges();

                    TempData["MSG"] = "success|Tipo atualizado com sucesso";
                    return Listar();
                }
                TempData["MSG"] = "warning|Preencha todos os campos|x";
                return Listar();
            }
            catch (Exception)
            {
                @TempData["MSG"] = "error|Impossível registrar dois tipos com o mesmo nome!|x";
                return Listar();
            }
        }

        [AcceptVerbs(HttpVerbs.Post), ValidateInput(false)]
        public JsonResult TrocarStatus(string id)
        {
            ManutencaoTipo tp = db.ManutencaoTipo.Find(Convert.ToInt32(id));

            if (tp != null)
            {
                if (tp.StatusId == db.Status.Where(x => x.Nome == "Ativado").FirstOrDefault().Id)
                {
                    tp.StatusId = db.Status.Where(x => x.Nome == "Desativado").FirstOrDefault().Id;
                }
                else
                {
                    tp.StatusId = db.Status.Where(x => x.Nome == "Ativado").FirstOrDefault().Id;
                }

                db.Entry(tp).State = EntityState.Modified;
                db.SaveChanges();

                return Json(tp.StatusId == db.Status.Where(x => x.Nome == "Ativado").FirstOrDefault().Id ? "t" : "f");
            }
            else
            {
                return Json("n");
            }
        }
        [AcceptVerbs(HttpVerbs.Post), ValidateInput(false)]
        public JsonResult Remover(string id)
        {
            try
            {
                string newId = "";
                if (id.Contains("_"))
                {
                    newId = id.Substring(7);
                }
                else
                {
                    newId = id;
                }
                ManutencaoTipo tp = db.ManutencaoTipo.Find(Convert.ToInt32(newId));

                if (tp != null)
                {

                    if (id != "remove_" + tp.Id)
                    {
                        if (tp.StatusId == db.Status.Where(s => s.Nome == "Ativado").FirstOrDefault().Id)
                        {
                            @TempData["MSG"] = "error|Não é possível excluir um tipo com status ATIVADO!|x";
                            return Json("f");
                        }
                    }

                    db.ManutencaoTipo.Remove(tp);
                    db.SaveChanges();
                    @TempData["MSG"] = "success|Tipo removido com sucesso!|x";
                    return Json(tp != null ? "t" : "f");

                }
                else
                {
                    @TempData["MSG"] = "error|Erro ao excluir o tipo!|x";
                    return Json("f");
                }

            }
            catch (Exception)
            {
                @TempData["MSG"] = "error|Impossível excluir este tipo, pois existem dados vinculados!|x";
                return Json("f");
            }
        }
    }
}

NGT/Areas/Admin/Views/ManutencaoTipo/EditaManutTipos.cshtml
@model NGT.Models.Entities.ManutencaoTipo
@{
    Layout = null;
}

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title txtBlack" id="EditaTipo">Edição de Tipos</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="overflow-hidden">

            @using (Html.BeginForm("EditaTipos", "ManutencaoTipo", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="modal-footer col-11 col-md-12 m-0 pb-0 justify-content-between">
                    <div>
                        <label class="control-label text-muted">ID de registro:</label>
                        @ViewBag.Tipos.Id
                    </div>

                    <a ref="remove_@ViewBag.Tipos.Id" class="btn btn-danger btn-sm remTip">
                        <i class="fas fa-trash"></i>
                        Excluir
                    </a>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, "Nome: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                    <div class="col-md-12 pl-3 pr-3">
                        <input type="text" name="Nome" class="form-control col-11 col-md-12" value="@ViewBag.Tipos.Nome">
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group m-0">
                    @Html.LabelFor(model => model.StatusId, "Status: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                    <div class="col-md-12 pl-3 pr-3">
                        @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control col-11 col-md-12" })
                    </div>
                </div>

                <div class="modal-footer col-11 col-md-12">
                    <button type="submit" class="btn btn-default float-right">
                        <i class="fas fa-solid fa-floppy-disk"></i>
                        Salvar
                    </button>
                </div>

            }

        </div>
    </div>
</div>

<script>
        $(".remTip").click(function () {
            var id = $(this).attr("ref");
            Swal.fire({
                title: 'Deseja confirmar a exclusão deste Motivo?',
                text: "Todos os dados serão apagados. Esta ação não pode ser desfeita!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Sim, excluir!'
            }).then((result) => {
                if (result.isConfirmed) {

                    $.ajax({
                        dataType: "json",
                        type: "POST",
                        url: "/admin/manutencaotipo/remove-tipo",
                        data: { id },
                        success: function (retorno) {

                            if (retorno == "t") {

                                window.location.replace("/admin/manutencaotipo");

                                    }
                                    else if (retorno == "f") {

                                        window.location.replace("/admin/manutencaotipo");
                            }
                        }
                    });
                }
            })


        });
    </script>
@section ScriptPage {

}

NGT/Areas/Admin/Views/ManutencaoTipo/ListaManutTipos.cshtml
@model NGT.Models.Entities.ManutencaoTipo
@{
    ViewBag.Title = "Tipos de Manutenção";
    ViewBag.MenuLinkTipo = true;
}

<section class="content-header pt-2">
    <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="@Url.RouteUrl("Admin.Dashboard.Index")">Admin</a></li>
                <li class="breadcrumb-item active">@ViewBag.Title</li>
            </ol>
        </div>
    </div>
</section>

<section class="pl-3 pr-3">
    <div class="row">
        <div class="col-sm-6 mb-3">

            <form action="@Url.RouteUrl("Admin.ManutencaoTipo.Filtrar")" method="get" role="search" class="d-inline">
                <div class="input-group input-group-sm">
                    <input class="form-control" type="text" name="termo" placeholder="Buscar">
                    <div class="input-group-append">
                        <button class="btn input-group-text" type="submit">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </form>

        </div>
        <div class="col-sm-6 mb-3">
            @if (@TempData["LP"] != null)
            {
                <a href="/admin/manutencaotipo" class="btn btn-default btn-sm float-lg-left float-md-left float-sm-left float-left mr-3">
                    Limpar
                </a>
            }
            <a class="btn btn-primary btn-sm float-lg-right float-md-right float-sm-right float-left" id="novoTipo">
                Novo Tipo
            </a>
        </div>
    </div>
</section>

<div class="pl-3 pr-3 pb-3">

    <div class="row d-flex justify-content-center align-items-center">
        @foreach (var item in @ViewBag.tipos)
        {
            var totItens = 0;
            bool status;
            if (item.Status.Nome == "Ativado")
            {
                status = true;
            }
            else
            {
                status = false;
            }



            foreach (var i in ViewBag.os)
            {
                if (i.ManutencaoTipoId == item.Id)
                {
                    totItens = totItens + 1;
                }
            }


            <div class="col-md-4 col-sm-6 col-lg-4 col-xl-2 col-6">

                <div class="card card-widget widget-user card-category">
                    <div class="widget-user-header bg-gradient-info">

                        <div class="editLoc">
                            <button ref="@item.Id" class="btn btn-tool editaTip">
                                <i class="fas fa-pencil-alt"></i>
                            </button>
                        </div>

                        <div class="removeLoc">
                            <button ref="@item.Id" class="btn btn-tool removeTip">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>

                        <h3 class="widget-user-username">@item.Nome</h3>
                    </div>

                    <div class="card-footer categorias">
                        <div class="row">
                            <div class="col-6 border-right">
                                <div class="description-block">
                                    <h5 class="description-header">
                                        @Html.CheckBox("chk", status, new { @class = "status", @rel = @item.Id })
                                        <span id="status_@item.Id">@item.Status.Nome</span>
                                    </h5>
                                    <span class="description-text">Status</span>
                                </div>

                            </div>

                            <div class="col-6">
                                <div class="description-block">
                                    <h5 class="description-header">
                                        @totItens
                                    </h5>
                                    <span class="description-text">Ordens de Serviços</span>
                                </div>

                            </div>

                        </div>

                    </div>
                </div>

            </div>
        }
    </div>

</div>

<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="NovoTipo" aria-hidden="true"></div>
<div id="modalE" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="EditaTipo" aria-hidden="true"></div>

@section ScriptPage {
    <script src="~/Areas/Admin/Content/Libs/bs-custom-file-input/bs-custom-file-input.min.js"></script>

    <script>
            $(function () {
                $('#novoTipo').click(function () {
                    $("#modal").load("@Url.RouteUrl("Admin.ManutencaoTipo.Novo")", function () {
                        $("#modal").modal();
                    });
                });
            });
    </script>
    <script>
        $(function () {
            $('.editaTip').click(function () {
                var id = $(this).attr("ref");
                $("#modalE").load("/admin/manutencaotipo/editatipos/" + id, function () {
                    $("#modalE").modal();
                });
            });
        });</script>
    <script>
        $(".status").click(function () {
            var id = $(this).attr("rel");
            $.ajax({
                dataType: "json",
                type: "POST",
                url: "/admin/manutencaotipo/trocarstatus",
                data: { id },
                success: function (retorno) {

                    if (retorno == "t") {
                        $("#status_" + id).removeClass("font-weight-bold text-danger");
                        $("#status_" + id).addClass("font-weight-bold text-success");
                        $("#status_" + id).text("Ativado");
                    }
                    else if (retorno == "f") {
                        $("#status_" + id).removeClass("font-weight-bold text-success");
                        $("#status_" + id).addClass("font-weight-bold text-danger");
                        $("#status_" + id).text("Desativado");

                    } else if (retorno == "n") {
                        window.location.replace("/admin/locais");
                    }
                }
            });
        });</script>
    <script>
        $(".removeTip").click(function () {
                var id = $(this).attr("ref");

                Swal.fire({
                    title: 'Deseja confirmar a exclusão deste Tipo?',
                    text: "Todos os dados serão apagados. Esta ação não pode ser desfeita!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    cancelButtonText: 'Cancelar',
                    confirmButtonText: 'Sim, excluir!'
                }).then((result) => {
                    if (result.isConfirmed) {

                        $.ajax({
                            dataType: "json",
                            type: "POST",
                            url: "/admin/manutencaotipo/remove-tipo",
                            data: { id },
                            success: function (retorno) {

                                if (retorno == "t") {

                                    window.location.replace("/admin/manutencaotipo");

                                }
                                else if (retorno == "f") {

                                    window.location.replace("/admin/manutencaotipo");
                                }
                            }
                        });
                    }
                })

            });</script>
}

NGT/Areas/Admin/Views/ManutencaoTipo/NovoManutTipos.cshtml
@model NGT.Models.Entities.ManutencaoTipo
@{
    Layout = null;
}

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title txtBlack" id="NovoTipo">Cadastro de Novos Tipos de Manutenção</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="overflow-hidden">

            @using (Html.BeginForm("Novo", "ManutencaoTipo", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, "Nome: ", htmlAttributes: new { @class = "control-label pl-3 pt-3" })
                    <div class="col-md-12 pl-3 pr-3">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control col-11 col-md-12" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="modal-footer justify-content-end col-11 col-md-12">
                    <button type="submit" class="btn btn-default ">Gravar</button>
                </div>

            }
        </div>
    </div>
</div>


@section ScriptPage {

}